### ISSUE TITLE
Prefered way to do several idependent runs

### ISSUE THREAD

**Issue by sschmeier** [snakemake-workflows/rna-seq-star-deseq2#15]
Hey @johanneskoester 

Question not an issue.

I try to understand what the best way currently is to use this workflow in independent analyses.
Do you clone the repo new when doing a new analyses? 
Do you run it in a subfolder like the .test one?

In my other workflows I define a base/result dir variable in the config.yaml that the Snakefile will use, where all results/logs/benchmarks for one run will be collected. Thus, doing a new analysis is as simple as creating a new config.yaml and changing the base/result dir variable in it.

Just wondering how you use this workflow in the best way.

Cheers,
    Seb

**Comment by johanneskoester** [comment]
I do the following (probably this should go into the readmes):

1. Fork the repo to a personal or lab account.
2. Create a new branch for the concrete project/run.
3. Modify the config (and probably the workflow) as needed.
4. Run the analysis.
5. Merge back any valuable and generalizable changes to the main repo.

The branch in the fork is kept, such that I can at any time look up or branch from the code I used for that particular run.

**Comment by sschmeier** [comment]
Good to know. The problem for me is that this requires me to move the results every time I completed a run our of the folders, e.g. star, counts, deseq2,....
For me, especially when using it over and over without much modification, except the samplesheet, units and config, it seems easier to just have the results of each run automatically collect in a separate folder based on a variable in the config.  My local version of this workflow does this and it works well for me... anyways I see your point as well...

**Comment by johanneskoester** [comment]
I don't think there is a need to move results. Let me adapt my post above.

**Comment by johanneskoester** [comment]
1. Fork the repo to a personal or lab account.
2. Clone the fork to the desired working directory for the concrete project/run.
3. Create a new branch within the clone.
4. Modify the config (and probably the workflow) as needed.
5. Commit any changes and push them to the fork. 
4. Run the analysis.
5. Merge back any valuable and generalizable changes to the main repo.

**Comment by johanneskoester** [comment]
Does that make more sense? So there is a folder on disk for every project/run. And there is a corresponding branch in the fork. Git allows to maintain that connection.

**Comment by johanneskoester** [comment]
Another important property is that you

1. never get side effects on other projects when you change something in your current one.
2. Git/Github allows you to keep track of the differences, and makes it very easy and transparent to migrate improvements in one project to the others.

**Comment by sschmeier** [comment]
Yes it makes sense. But in my mind what you describe is the development phase of the workflow.

At some point I have a working workflow. But now I need to apply it over and over again to different projects. What I cannot have is 100 folders on disk that all contain the repo and once the run is done with it all the conda envs, the singularity image, etc. Its just too much data. On top it takes time to rebuild the envs every time in every new "project" folder

I work in one folder that contains the repo and the workflow files and the conda envs and/or singularity image are all ready to go (from the very first run). I just create a new config that points to sample and unit sheets (normally not in he same folder but somewhere else) and output dir (might also be somewhere else, maybe where the sample and unit sheets are) and of you go and run the workflow. Downside is only one run at a time. So a new project needs to wait until the last run is finished...

**Comment by johanneskoester** [comment]
Not necessarily. You never know what happens in a particular project. It might be that you just did not foresee that a particular plot has to be altered (axis limits, coloring, etc.). You don't want that to end up undocumented without version control. Or worse, affect reruns of other projects.

However, I don't see a contradiction with your needs, let me reformulate:

1. Fork the repo to a personal or lab account.
2. Clone the fork to the desired working directory for the concrete project/run.
3. Create a new branch within the clone.
4. Modify the config (and probably the workflow) as needed.
5. Commit any changes and push them to the fork. 
6. Run the analysis.
7. Optional: Merge back any valuable and generalizable changes to the main repo.
8. Optional: Push results (plots/tables) to the remote branch.
9. Optional: Create a self-contained workflow archive for publication along with the paper (snakemake --archive).
10. Optional: Delete the local clone/workdir to free space.

The time to create the conda envs (at least with the workflows we have here) should always be minor compared to the runtime of the analysis. If all clones of the project are on the same machine, conda will reuse packages via symlinking and hardlinking. So the environments in the working directory should be rather lightweight. Finally deletion of the workdir is not an issue since the entire changes (and possibly the main results) are in the remote git branch and optionally also in the workflow archive.

**Comment by johanneskoester** [comment]
Does that mean you agree? Any final thoughts? Otherwise, I would include the concept in the docs.

**Comment by sschmeier** [comment]
Yes I agree. 

Some suggestions:

3. Maybe name it a project-branch?
4. should include changes to sample-sheet and unit-sheet. 
I would swap 5. and 6., ie only push if the run is successful (could then include 8. here)?
5. I think you mean push the "project"-branch to the fork remote for safe keeping?
7. with main repo you mean "upstream" to stay in github speak?
