### ISSUE TITLE
Costum genome as reference

### ISSUE THREAD

**Issue by seb-mueller** [snakemake-workflows/rna-seq-star-deseq2#55]
It appears as if only genomes listed on ensemble [1] are supported.
If the species of interest is not listed, is it possible to use a costum fasta/gff combination instead?

[1] ftp://ftp.ensembl.org/pub

**Comment by dlaehnemann** [comment]
This is intentional, to have a workflow as reproducible as possible from the start. The problem with using some manually downloaded genome fasta/gff is that no one else will know where you got it from (unless you take great care to document this in a way that people are sure to find this information, which is actually pretty hard to achieve, in my experience). With that cautionary note out of the way: you can of course simply provide the file `"resources/genome.fasta"` or `"resources/genome.gtf"` in the correct location, and the workflow should just pick it up (assuming that it's the output of the respective rule).
